In [3]:
import numpy as np

# Создание массива из обычного списка Python
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Создание двумерного массива из вложенных списков
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

# Создание массива, заполненного нулями
zeros_arr = np.zeros(5)
print(zeros_arr)

# Создание двумерного массива, заполненного единицами
ones_arr = np.ones((3, 4))
print(ones_arr)

# Создание массива с последовательностью чисел
range_arr = np.arange(0, 10, 2)
print(range_arr)


print("Массив:", arr2d)
print("Форма (shape):", arr2d.shape)  # Размеры массива
print("Тип данных (dtype):", arr2d.dtype)  # Тип элементов


# Одномерный массив для демонстрации
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Исходный массив:", arr)
print("Первый элемент (индекс 0):", arr[0])
print("Последний элемент (индекс -1):", arr[-1])
print("Третий элемент (индекс 2):", arr[2])

print("Срез [2:5]:", arr[2:5])  # элементы с индексами 2, 3, 4
print("Срез [:4]:", arr[:4])    # первые 4 элемента
print("Срез [5:]:", arr[5:])    # элементы с индекса 5 до конца
print("Срез [::2]:", arr[::2])  # каждый второй элемент


print("Исходный массив", arr2d)
print("Элемент [1,2]:", arr2d[1, 2])  # строка 1, столбец 2
print("Вторая строка:", arr2d[1, :])   # вся строка 1
print("Первый столбец:", arr2d[:, 0])  # весь столбец 0

# Срез в двумерном массиве
print("Срез первых двух строк и двух столбцов:")
print(arr2d[:2, :2])


# Создаем два массива для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Массив a:", a)
print("Массив b:", b)

# Поэлементные операции
print("a + b =", a + b)  # поэлементное сложение
print("a * b =", a * b)  # поэлементное умножение
print("b - a =", b - a)  # поэлементное вычитание
print("b / a =", b / a)  # поэлементное деление

# Операции с скаляром
print("a * 2 =", a * 2)    # умножение на скаляр
print("a + 10 =", a + 10)  # сложение со скаляром


data = np.array([2, 4, 6, 8, 10, 12])
print("Данные:", data)

print("Среднее значение (mean):", np.mean(data))
print("Медиана (median):", np.median(data))
print("Стандартное отклонение (std):", np.std(data))
print("Минимальное значение (min):", np.min(data))
print("Максимальное значение (max):", np.max(data))
print("Сумма всех элементов (sum):", np.sum(data))



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
Массив: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма (shape): (3, 3)
Тип данных (dtype): int64
Исходный массив: [10 20 30 40 50 60 70 80]
Первый элемент (индекс 0): 10
Последний элемент (индекс -1): 80
Третий элемент (индекс 2): 30
Срез [2:5]: [30 40 50]
Срез [:4]: [10 20 30 40]
Срез [5:]: [60 70 80]
Срез [::2]: [10 30 50 70]
Исходный массив [[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [1,2]: 6
Вторая строка: [4 5 6]
Первый столбец: [1 4 7]
Срез первых двух строк и двух столбцов:
[[1 2]
 [4 5]]
Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
a + b = [ 6  8 10 12]
a * b = [ 5 12 21 32]
b - a = [4 4 4 4]
b / a = [5.         3.         2.33333333 2.        ]
a * 2 = [2 4 6 8]
a + 10 = [11 12 13 14]
Данные: [ 2  4  6  8 10 12]
Среднее значение (mean): 7.0
Медиана (median): 7.0
Стандартное отклонение (std): 3.415650255319866
Минимальное значение (min): 2
Максимальное значение (max): 12
Сумма всех элементо